// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA99FxJPF6SJldNW7UBEW4ffyzx4Gs7JFE',
    appId: '1:809687675147:web:07937ff8b594b8ce48720e',
    messagingSenderId: '809687675147',
    projectId: 'prueba-p3-d2cda',
    authDomain: 'prueba-p3-d2cda.firebaseapp.com',
    storageBucket: 'prueba-p3-d2cda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWo20eieNqzY2ckbJl0vzTqIIDc6Z_mY',
    appId: '1:809687675147:android:c9d7f5756f7cd8fe48720e',
    messagingSenderId: '809687675147',
    projectId: 'prueba-p3-d2cda',
    storageBucket: 'prueba-p3-d2cda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisiUjhZ-C8sxven8ovpHMNvFW2orKOrM',
    appId: '1:809687675147:ios:2013fdbec362e3a548720e',
    messagingSenderId: '809687675147',
    projectId: 'prueba-p3-d2cda',
    storageBucket: 'prueba-p3-d2cda.firebasestorage.app',
    iosBundleId: 'com.example.autenticacionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA99FxJPF6SJldNW7UBEW4ffyzx4Gs7JFE',
    appId: '1:809687675147:web:a8e6fe118af5d8ed48720e',
    messagingSenderId: '809687675147',
    projectId: 'prueba-p3-d2cda',
    authDomain: 'prueba-p3-d2cda.firebaseapp.com',
    storageBucket: 'prueba-p3-d2cda.firebasestorage.app',
  );
}
